import test from 'node:test';
import assert from 'node:assert/strict';

import {
  formatBotIpSyncHelp,
  formatBotIpSyncSummary,
  parseBotIpSyncArgs,
  runBotIpSync
} from '../src/ops/sync-bot-ip-file.js';

test('parseBotIpSyncArgs reads repeated sources and dry-run mode', () => {
  assert.deepEqual(
    parseBotIpSyncArgs([
      '--source-url',
      'https://intel.example/bots.txt',
      '--source-file=local-bots.txt',
      '--output',
      'config/bot-ips.txt',
      '--dry-run'
    ]),
    {
      sourceUrls: ['https://intel.example/bots.txt'],
      sourceFiles: ['local-bots.txt'],
      output: 'config/bot-ips.txt',
      dryRun: true,
      help: false
    }
  );
});

test('formatBotIpSyncHelp documents source URL, source file, output, and dry-run', () => {
  const help = formatBotIpSyncHelp();

  assert.match(help, /Bot IP Sync CLI/);
  assert.match(help, /--source-url/);
  assert.match(help, /--source-file/);
  assert.match(help, /--output/);
  assert.match(help, /--dry-run/);
});

test('formatBotIpSyncSummary includes source count, output, and mode', () => {
  const summary = formatBotIpSyncSummary({
    sourceCount: 2,
    output: 'config/bot-ips.txt',
    botIps: ['66.249.66.1', '203.0.113.10'],
    dryRun: false
  });

  assert.match(summary, /Bot IP sync completed/);
  assert.match(summary, /Sources: 2/);
  assert.match(summary, /Output: config\/bot-ips\.txt/);
  assert.match(summary, /Count: 2/);
  assert.match(summary, /Mode: write/);
});

test('runBotIpSync normalizes URL and file sources into one output file', async () => {
  const calls = [];
  const result = await runBotIpSync({
    argv: [
      '--source-url',
      'https://intel.example/bots.txt',
      '--source-file',
      'local-bots.txt',
      '--output',
      'config/bot-ips.txt'
    ],
    stdout: { write(message) { calls.push({ type: 'stdout', message }); } },
    stderr: { write(message) { calls.push({ type: 'stderr', message }); } },
    fetch: async (url) => {
      calls.push({ type: 'fetch', url });
      return {
        status: 200,
        text: async () => '# upstream\n66.249.66.1\n203.0.113.10\n'
      };
    },
    readFile: async (path) => {
      calls.push({ type: 'readFile', path });
      return '203.0.113.10\n198.51.100.7\n';
    },
    writeFile: async (path, content) => {
      calls.push({ type: 'writeFile', path, content });
    },
    mkdir: async (path) => {
      calls.push({ type: 'mkdir', path });
    }
  });

  assert.equal(result.exitCode, 0);
  assert.deepEqual(result.botIps, ['66.249.66.1', '203.0.113.10', '198.51.100.7']);
  assert.ok(calls.some((call) => call.type === 'fetch' && call.url === 'https://intel.example/bots.txt'));
  assert.ok(calls.some((call) => call.type === 'readFile' && call.path === 'local-bots.txt'));

  const write = calls.find((call) => call.type === 'writeFile');
  assert.equal(write.path, 'config/bot-ips.txt');
  assert.equal(write.content, [
    '# Generated by npm run bot-ips:sync',
    '66.249.66.1',
    '203.0.113.10',
    '198.51.100.7',
    ''
  ].join('\n'));
});

test('runBotIpSync dry-run reports the result without writing output', async () => {
  const calls = [];
  const result = await runBotIpSync({
    argv: [
      '--source-url=https://intel.example/bots.txt',
      '--output=config/bot-ips.txt',
      '--dry-run'
    ],
    stdout: { write(message) { calls.push({ type: 'stdout', message }); } },
    stderr: { write(message) { calls.push({ type: 'stderr', message }); } },
    fetch: async () => ({
      status: 200,
      text: async () => '66.249.66.1\n'
    }),
    writeFile: async () => {
      calls.push({ type: 'writeFile' });
    }
  });

  assert.equal(result.exitCode, 0);
  assert.deepEqual(result.botIps, ['66.249.66.1']);
  assert.ok(calls.some((call) => call.type === 'stdout' && call.message.includes('Mode: dry-run')));
  assert.ok(!calls.some((call) => call.type === 'writeFile'));
});

test('runBotIpSync returns exitCode 1 when required arguments are missing', async () => {
  const calls = [];
  const result = await runBotIpSync({
    argv: ['--output', 'config/bot-ips.txt'],
    stdout: { write(message) { calls.push({ type: 'stdout', message }); } },
    stderr: { write(message) { calls.push({ type: 'stderr', message }); } }
  });

  assert.equal(result.exitCode, 1);
  assert.match(result.error.message, /At least one --source-url or --source-file is required/);
  assert.ok(calls.some((call) => call.type === 'stderr'));
});
